development:
    adapter: mysql2
    encoding: utf8
    database: greywire
    username: greywire
    password: greywire

production:
    adapter: mysql2
    encoding: utf8
    database: greywire
    username: greywire
    password: greywire
